name: Docker and Integration Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.3.0'
          java: 'java17'
      - name: Install Native Image
        run: gu install native-image
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: ./gradlew check dockerBuildNative --no-daemon
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run POSTMAN collection
        run: |
          docker run -d -p 8080:8080 reference-data:latest
          mkdir -p build/testResults
          newman run ./src/test/postman/IntegrationTests.postman_collection.json -e ./src/test/postman/Localhost.postman_environment.json -r htmlextra --reporter-htmlextra-export build/testResults/htmlreport.html --reporter-htmlextra-darkTheme > build/testResults/runreport1.html
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: build/testResults
      - name: Push Docker Image
        env:
          DOCKER_REPOSITORY_PATH: ${{ secrets.DOCKER_REPOSITORY_PATH }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          docker tag reference-data:latest $DOCKER_REGISTRY_URL/$DOCKER_REPOSITORY_PATH:latest
          docker push $DOCKER_REGISTRY_URL/$DOCKER_REPOSITORY_PATH:latest